# Step 1 build  proyect the  node-React

FROM alpine:3.16 AS build
ENV NODE_VERSION 16.18.1
WORKDIR /APP
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build 

# Step 2  create serv nginx server

FROM alpine:3.16 AS prod-stage
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD [ "nginx","-g","daemon off" ]