# Step 1 build  proyect the  node-React

FROM node:12-alpine3.12 AS build
WORKDIR /APP
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build 

# Step 2  create serv nginx server

FROM nginx:1.19.0-alpine AS prod-stage
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD [ "nginx","-g","daemon off" ]