on:
  push:
    branches:
      - "main"
name: deploy
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: DOCKER_USERNAME
          password: DOCKER_PASSWORD

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pindevops:latest
  # deploy-to-cluster:
  #   name: deploy to cluster
  #   runs-on: ubuntu-latest
  #   needs: build-and-push
  #   steps:
  #   - name: deploy to cluster
  #     uses: steebchen/kubectl@master
  #     env:
  #       KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  #     with:
  #       args: set image --record deployment/my-app prueba-gha=${{ github.repository }}:${{ github.sha }}
  #   - name: verify deployment
  #     uses: steebchen/kubectl@master
  #     env:
  #       KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  #       KUBECTL_VERSION: "1.20"
  #     with:
  #       args: '"rollout status deployment/my-app"'
  # ngrok-watcher:
  #   name: Ngrok watcher
  #   runs-on: ubuntu-latest
  #   needs: deploy-to-cluster
  #   steps:
  #   - name: Get ngrok URL
  #     id: getNgrokUrl
  #     uses: debianmaster/kubectl@master
  #     env:
  #       KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  #       KUBECTL_VERSION: "1.20"
  #     with:
  #       args: |
  #         URL=`kubectl -n prueba get ngrok -o=custom-columns='DATA:status.url' | tail -n1`
  #         echo "::set-output name=url::$URL"
  # - name: Check if URL is valid
  #   uses: ubuntu-latest
  #   run: |
  #     echo "URL is: ${{ steps.getNgrokUrl.outputs.url }}"
  # - name: Watch ngrok
  # uses: steebchen/kubectl@master
  # env:
  #   KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  #   KUBECTL_VERSION: "1.20"
  # run: echo "Hello world"
  # # with:
  # #   args: '"rollout status deployment/my-app"'
